# Compiler
CXX = g++

# Compiler flags
CXXFLAGS = -Wall -Wextra -std=c++11

# Linker flags (if needed)
LDFLAGS =

# Executable name
EXECUTABLE = dijkstra

# Source files (main program and class implementations)
SOURCES = main.cpp graph.cpp minheap.cpp

# Object files (generated by compiling source files)
OBJECTS = $(SOURCES:.cpp=.o)

# Targets
all: $(EXECUTABLE)

# Linking the executable
$(EXECUTABLE): $(OBJECTS)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $(OBJECTS)

# Compiling source files into object files
%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c -o $@ $<

# Clean rule
clean:
	rm -f $(EXECUTABLE) $(OBJECTS)
